services:
  db:
    image: postgis/postgis:16-3.4
    container_name: geo_postgis_db
    environment:
      POSTGRES_DB: geoanalytics
      POSTGRES_USER: shmeetoo
      POSTGRES_PASSWORD: 1905
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: