services:
  db:
    image: postgis/postgis:16-3.4
    container_name: geo-accessibility-db
    restart: unless-stopped
    env_file:
      - ../.env.docker
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dashboard:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: geo-accessibility-dashboard
    restart: unless-stopped
    env_file:
      - ../.env.docker  
    ports:
      - "8050:8050"
    depends_on:
      - db
    command: >
      sh -c "
      if [ ! -f /app/.pipeline_done ]; then
        echo 'Running pipeline...';
        python -m scripts.run_pipeline;
        touch /app/.pipeline_done;
      else
        echo 'Pipeline already executed';
      fi &&
      python -m app.dashboard
      "
volumes:
  postgres_data: