DISTRICT_NAME_MAPPING = {
    "Bemowo": "Bemowo",
    "Bialoleka": "Białołęka",
    "Białołęka": "Białołęka",
    "Bielany": "Bielany",
    "Mokotow": "Mokotów",
    "Mokotów": "Mokotów",
    "Ochota": "Ochota",
    "Praga-Polnoc": "Praga-Północ",
    "Praga-Północ": "Praga-Północ",
    "Praga-Poludnie": "Praga-Południe",
    "Praga-Południe": "Praga-Południe",
    "Praga Polnoc": "Praga-Północ",
    "Praga Północ": "Praga-Północ",
    "Praga Poludnie": "Praga-Południe",
    "Praga Południe": "Praga-Południe",
    "Rembertow": "Rembertów",
    "Rembertów": "Rembertów",
    "Srodmiescie": "Śródmieście",
    "Śródmieście": "Śródmieście",
    "Targowek": "Targówek",
    "Targówek": "Targówek",
    "Ursus": "Ursus",
    "Ursynow": "Ursynów",
    "Ursynów": "Ursynów",
    "Wawer": "Wawer",
    "Wesola": "Wesoła",
    "Wesoła": "Wesoła",
    "Wilanow": "Wilanów",
    "Wilanów": "Wilanów",
    "Wlochy": "Włochy",
    "Włochy": "Włochy",
    "Wola": "Wola",
    "Zoliborz": "Żoliborz",
    "Żoliborz": "Żoliborz",
}